inp = 'TATAGGTTTCCCCGATGCTACCCGGAGGAAAGCCGACTTTCGACTTCAGGGACGTCCAGCCTTTGTAATTGTACCGAGAAGATTAAGCAGAATGCACCAGGCGGAACGGAATTACAAACTTGCACTTAGGAGGAAATAGCGGCGCAACTGGCGGTACACCCCAGCTCATTAGACCAGGGTCAAGGTCTTCGAACGTCCTACCCTGTACCTTTAAGGGAATGATACCCTAGTGCCGCCGATTTGTCGTTACATGTAACGCGGATTGGCAAAGGGTGAGCATTTTCAATAGCTTGAGTTTGTGAGGCCCACGCTCATCACGTACAGTGCACCCTGGCCCCTACGAGAGGGCTCGACATGGGTCGACTGAGGTACAGTCATTAATGTACACTCAAGAAGTCGGCTGTCGTCATTTACATAACTGACGTCAAGGACCATCTTCGGCGATACGACCTCGCCGGCGGTCGTAGGTGCGAGGATGAAGGGTATGAAGCAGTATTTTCTTACACACTCTAATGGCGGAACTACGTCAGCGTGGGTGGTGACGAGGCTGGGCTGCGTCGCCGCCCCTAATTTGTGACCCTGCTGCTGATAGGCACATTCCAATATAGTGGCGAAAGCCGCAACTCCATATCACCCGATCTTATCGCGGATTGCTCGGGTTCCTCTATCACTCCATGCGGTGATAGCCCGATTCTTCGCGCGAGCATCAGGATCACACGCCAATAGTAGCGGGATAGGAGCGTGCAGGTATCCAATAGCGCTCAGATCAATAAGAGTGGCAAGCCGTAGGCCTCGAGCTGAGACAAACGTTAAGCTCCTCCTATTTATCCGCGGAGCAGAAAGTAGCATGTCTCAAACAAGCTCTGTAGGGGCGAGGATTTCAACGCAATCCCACCTTCG'
a= 0
g = 0
t = 0
c = 0
for x in inp:
    if x == 'A':
        a = a + 1
    if x == 'T':
        t = t + 1
    if x == 'C':
        c = c + 1
    if x == 'G':
        g = g + 1
out = str(a) + ' ' + str(c) + ' ' + str(g) + ' ' + str(t) 
print(out)
